# Generated by Django 4.0.5 on 2022-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='time_of',
            field=models.CharField(max_length=100),
        ),
    ]
