# Generated by Django 4.0.5 on 2022-06-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sighting_time_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='user',
        ),
    ]
