# Generated by Django 4.0.5 on 2022-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_sighting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
